# Generated by Django 5.1.1 on 2024-09-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resume', '0002_rename_name_resume_field_type_resume_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
